import type { Quiz, MultipleChoiceQuestion } from '@/types/exercise';

const treesQuestions: MultipleChoiceQuestion[] = [
  {
    id: 'trees-1',
    type: 'multiple-choice',
    title: 'Max Nodes in Binary Tree',
    description: 'Binary tree node count',
    topic: 'trees',
    difficulty: 'intermediate',
    points: 10,
    question: 'What is the maximum number of nodes in a binary tree of height h?',
    options: ['h + 1', '2^h', '2^(h+1) - 1', '2^h + 1'],
    correctAnswer: 2,
    explanation: 'A perfect binary tree of height h has 2^(h+1) - 1 nodes. For example, height 2: 1 + 2 + 4 = 7 = 2^3 - 1.',
  },
  {
    id: 'trees-2',
    type: 'multiple-choice',
    title: 'Root-First Traversal',
    description: 'Identifying traversal orders',
    topic: 'trees',
    difficulty: 'beginner',
    points: 10,
    question: 'Which traversal visits the root first?',
    options: ['In-order', 'Pre-order', 'Post-order', 'None of the above'],
    correctAnswer: 1,
    explanation: 'Pre-order traversal visits the Root first, then Left, then Right. "Pre" means the root comes before (pre) the children.',
  },
  {
    id: 'trees-3',
    type: 'multiple-choice',
    title: 'BST Sorted Output',
    description: 'BST traversal property',
    topic: 'trees',
    difficulty: 'beginner',
    points: 10,
    question: 'Which traversal of a BST gives sorted output?',
    options: ['Pre-order', 'In-order', 'Post-order', 'Level-order'],
    correctAnswer: 1,
    explanation: 'In-order traversal (Left → Root → Right) of a BST visits nodes in ascending order because left children are always smaller and right children are always larger.',
  },
  {
    id: 'trees-4',
    type: 'multiple-choice',
    title: 'Leaf Node',
    description: 'Tree terminology',
    topic: 'trees',
    difficulty: 'beginner',
    points: 10,
    question: 'A node with no children is called a ___?',
    options: ['Root', 'Branch', 'Leaf', 'Sibling'],
    correctAnswer: 2,
    explanation: 'A leaf node (or terminal node) is a node with no children. It is at the "end" of a branch, like a leaf on a real tree.',
  },
  {
    id: 'trees-5',
    type: 'multiple-choice',
    title: 'Level-Order Data Structure',
    description: 'BFS traversal implementation',
    topic: 'trees',
    difficulty: 'intermediate',
    points: 10,
    question: 'What data structure does level-order traversal use?',
    options: ['Stack', 'Queue', 'Array', 'Hash Map'],
    correctAnswer: 1,
    explanation: 'Level-order traversal uses a queue (FIFO) to process nodes level by level. Each node\'s children are enqueued as the node is visited.',
  },
  {
    id: 'trees-6',
    type: 'multiple-choice',
    title: 'Complete Binary Tree Leaves',
    description: 'Counting leaves',
    topic: 'trees',
    difficulty: 'intermediate',
    points: 10,
    question: 'In a complete binary tree with 10 nodes, how many are leaves?',
    options: ['3', '4', '5', '6'],
    correctAnswer: 2,
    explanation: 'In a complete binary tree with n nodes, there are ⌈n/2⌉ leaves. For 10 nodes: ⌈10/2⌉ = 5 leaves.',
  },
  {
    id: 'trees-7',
    type: 'multiple-choice',
    title: 'Safe Tree Deletion',
    description: 'Choosing the right traversal',
    topic: 'trees',
    difficulty: 'intermediate',
    points: 10,
    question: 'Which traversal is used to safely delete an entire tree?',
    options: ['Pre-order', 'In-order', 'Post-order', 'Level-order'],
    correctAnswer: 2,
    explanation: 'Post-order traversal deletes children before the parent, ensuring no references are lost. If you delete the parent first, you lose access to its children.',
  },
  {
    id: 'trees-8',
    type: 'multiple-choice',
    title: 'Single Node Tree Height',
    description: 'Understanding tree height',
    topic: 'trees',
    difficulty: 'beginner',
    points: 10,
    question: 'What is the height of a tree with only one node (the root)?',
    options: ['-1', '0', '1', '2'],
    correctAnswer: 1,
    explanation: 'The height of a single-node tree is 0. Height is the number of edges on the longest path from root to a leaf. A single node has no edges below it.',
  },
];

export const treesQuiz: Quiz = {
  id: 'trees',
  title: 'Trees',
  description: 'Test your understanding of tree data structures, terminology, and traversal algorithms',
  questions: treesQuestions,
  timeLimit: 10,
  passingScore: 70,
  topic: 'trees',
};

export const allTreesQuizzes = [treesQuiz];
