import type { Quiz, MultipleChoiceQuestion } from '@/types/exercise';

const searchingQuestions: MultipleChoiceQuestion[] = [
  {
    id: 'search-1',
    type: 'multiple-choice',
    title: 'Linear Search Time Complexity',
    description: 'Understanding linear search performance',
    topic: 'searching',
    difficulty: 'beginner',
    points: 10,
    question: 'What is the time complexity of linear search?',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
    correctAnswer: 2,
    explanation: 'Linear search checks each element one by one, so in the worst case it examines all n elements, giving O(n) time complexity.',
  },
  {
    id: 'search-2',
    type: 'multiple-choice',
    title: 'Binary Search Prerequisite',
    description: 'Understanding binary search requirements',
    topic: 'searching',
    difficulty: 'beginner',
    points: 10,
    question: 'What must be true about an array to use binary search?',
    options: ['It must contain unique elements', 'It must be sorted', 'It must have an even length', 'It must contain positive numbers'],
    correctAnswer: 1,
    explanation: 'Binary search requires a sorted array because it relies on eliminating half the search space by comparing the middle element with the target.',
  },
  {
    id: 'search-3',
    type: 'multiple-choice',
    title: 'Binary Search Max Comparisons',
    description: 'Calculating maximum comparisons',
    topic: 'searching',
    difficulty: 'intermediate',
    points: 10,
    question: 'Binary search on 1,024 elements makes at most how many comparisons?',
    options: ['5', '10', '32', '512'],
    correctAnswer: 1,
    explanation: 'Binary search makes at most log₂(n) comparisons. log₂(1024) = 10, so at most 10 comparisons are needed.',
  },
  {
    id: 'search-4',
    type: 'multiple-choice',
    title: 'Search on Linked Lists',
    description: 'Data structure compatibility',
    topic: 'searching',
    difficulty: 'beginner',
    points: 10,
    question: 'Which search algorithm works efficiently on a linked list?',
    options: ['Binary search', 'Linear search', 'Both work equally well', 'Neither works on linked lists'],
    correctAnswer: 1,
    explanation: 'Linear search works on linked lists because it only needs sequential access. Binary search requires random access (jumping to the middle), which linked lists cannot do efficiently.',
  },
  {
    id: 'search-5',
    type: 'multiple-choice',
    title: 'Binary Search: Target Greater',
    description: 'Understanding the binary search process',
    topic: 'searching',
    difficulty: 'intermediate',
    points: 10,
    question: 'In binary search, what happens when arr[mid] < target?',
    options: ['Search the left half', 'Search the right half', 'The element is found', 'The search terminates'],
    correctAnswer: 1,
    explanation: 'When arr[mid] < target, the target must be in the right half (if it exists), so we set low = mid + 1 and continue searching.',
  },
  {
    id: 'search-6',
    type: 'multiple-choice',
    title: 'Best Case of Linear Search',
    description: 'Best case analysis',
    topic: 'searching',
    difficulty: 'beginner',
    points: 10,
    question: 'What is the best case time complexity of linear search?',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
    correctAnswer: 0,
    explanation: 'The best case is O(1), which occurs when the target is the very first element in the array.',
  },
  {
    id: 'search-7',
    type: 'multiple-choice',
    title: 'Mid Calculation',
    description: 'Calculating mid index',
    topic: 'searching',
    difficulty: 'intermediate',
    points: 10,
    question: 'If binary search has low=3, high=9, what is mid?',
    options: ['5', '6', '7', '4'],
    correctAnswer: 1,
    explanation: 'mid = low + (high - low) / 2 = 3 + (9 - 3) / 2 = 3 + 3 = 6. Using this formula avoids integer overflow.',
  },
  {
    id: 'search-8',
    type: 'multiple-choice',
    title: 'Divide and Conquer Search',
    description: 'Identifying search strategies',
    topic: 'searching',
    difficulty: 'beginner',
    points: 10,
    question: 'Which search algorithm uses the divide-and-conquer strategy?',
    options: ['Linear search', 'Binary search', 'Both algorithms', 'Neither algorithm'],
    correctAnswer: 1,
    explanation: 'Binary search uses divide-and-conquer: it divides the search space in half at each step. Linear search simply scans sequentially.',
  },
];

export const searchingQuiz: Quiz = {
  id: 'searching',
  title: 'Searching Algorithms',
  description: 'Test your understanding of linear search and binary search algorithms',
  questions: searchingQuestions,
  timeLimit: 10,
  passingScore: 70,
  topic: 'searching',
};

export const allSearchingQuizzes = [searchingQuiz];
